export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCESS = 'LOGIN_SUCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';

export const REGISTER_UPDATE_SUCESS = 'REGISTER_UPDATE_SUCESS';
export const REGISTER_CREATE_SUCESS = 'REGISTER_CREATE_SUCESS';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
